version: "3.4"
services:
    bedbos_be:
        build:
            context: .
            target: production
        volumes:
            - .:/src
        command: npm run prod
        ports:
            - "3001:3000"
        environment:
            NODE_ENV: production
            DEBUG: nodejs-docker-express:* 
        restart: always